name: 'Update labels from PRs'
description: 'Set labels on PR from associated PRs'
inputs:
  current-pr-number:
    description: 'PR number on which labels must be set'
    required: true
  interesting-labels:
    description: 'Labels sought. Must be separated by , ie. ''infra,sqitch'''
    required: true
  repo-token:
    description: 'Github token to call API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'